baseURL = "https://gnuevo.github.io/kulthesis-site/"
publishDir = "docs"
languageCode = "en-us"
title = "Texture transfer master thesis"
theme = "hugo-theme-learn"
disableInlineCopyToClipBoard = true
disableShortcutsTitle = true
